### ISSUE TITLE
ModelBase GetHashCode throws exception if any property is Null

### ISSUE THREAD

**Issue by ebeisecker** [gehnster/EVEStandard#135]
GetHashCode() throws a null ref exception if any Property on a ModelBase object has a Null value.

Given that subclasses of ModelBase can be initialized with null values for their properties, GetHashCode() should not include null properties in it's calculation. 

```
var marketOrder = new EVEStandard.Models.MarketOrder();

marketOrder.GetHashCode(); // Throws exception 
```

**Comment by gehnster** [comment]
Sorry for taking so long to get back to this, I don't have notifications setup for issues here but will see about getting notifications in the Discord server in the future.

Too be honest, I'm not sure how to resolve this problem and likely only implemented ```GetHashCode``` because for Equals override, but didn't expect people to actually need it. Can I ask how you are using these models in hash tables for my own curiousity.

**Comment by ebeisecker** [comment]
The simple use case was I was trying to create a Dictionary where the key was a `EVEStandard.Model.Type`. 

The extended context was I'm using the `EVEStandard.Model` classes to map the result from querying the [EVE Static Data Export](https://developers.eveonline.com/resource)

**Comment by gehnster** [comment]
Thanks for the additional info. I'm not quite sure where the hash code is trying to be utilized in that example you provided, since I would think it would try to use the TypeId as the key instead of a hash code, but I can try to think up a solution to your problem if you want and if you had a suggestion I'm all ears!

Some things I'd like to note though:
1. TypeId in EVEStandard.Model.Type is nullable, could be causing an issue for ya if that was a direct copy and paste.
2. The models in the library are really NOT designed to be used as database models, especially because they were auto-generated for the most part by pulling the ESI swagger and only designed to be used to serialize the JSON received into concrete classes within C#. Just a quick comparison between my Type model and the InvTypes table and there are differences between the two so I would highly suggest either generating database or business logic models from the SDE to utilize in your program.
3. The models in EVEStandard are not versioned. What this means is when a version of an endpoint increments I update the model to support whatever changes it contains. Usually these are just additions but if it were a removal or a rename of something it could cause you issues in how you are trying to use them in your example.

I hope that helps!

**Comment by ebeisecker** [comment]
`GetHashCode()` is used by the `Dictionary` class to generate the value that is used for Key lookups. 

I agree that I'm not using the Models in a "Supported" way and any problems I have using them to map DB results will be my issue to deal with. 

Since the ModelBase objects do have Nullable properties, it should be possible to compare 2 ModelBase objects using GetHashCode. Currently, that isn't possible since GetHashCode() throws an exception when a Property of a ModelBase object is null. 

I think the `propertyInfo.GetValue(this).GetHashCode()` at https://github.com/gehnster/EVEStandard/blob/master/EEStandard/Models/ModelBase.cs#L74 is the issue since `propertyInfo.GetValue(this)` could be Null so that is where the Null ref occurs

**Comment by gehnster** [comment]
I'll try taking a closer look at this this weekend. Is the market order example you gave one where you encountered the error as I'll probably use that to replicate the bug.

Thanks

**Comment by gehnster** [comment]
I tested the first example you provided and was able to receive the null error. I've made a small change to hopefully fix this issue. https://github.com/gehnster/EVEStandard/pull/136
