### ISSUE TITLE
Inconsistent types. 

### ISSUE THREAD

**Issue by lstyles** [gehnster/EVEStandard#26]
CharacterInfo call takes characterId as long but returns characterInfo.characterId as int.

Same for alliance and corporations. Queries require long but the characterinfo returns ints.

Great library by the way.

**Comment by gehnster** [comment]
Yeah. The int vs long thing has been a pain, partly because the Swagger API doesn't always list what exactly something is on the ESI docs page without looking in the .json file which I didn't care to take the time to do.  I plan to fix this inconsistencies for version 2 of the library and have already started in some places.

**Comment by lstyles** [comment]
Should I send a PR?

**Comment by gehnster** [comment]
Feel free and I can take a look at it.

**Comment by lstyles** [comment]
This is fixed in 2.0.0-alpha nuget package
