### ISSUE TITLE
Problems building an Winforms app

### ISSUE THREAD

**Issue by nvpetrov** [gehnster/EVEStandard#69]
Hi,

I am trying to build an Winforms app, but when I run it, it throws an exception:

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Extensions.Logging.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Extensions.Logging.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'
   at EVEStandard.API.Alliance..ctor(String dataSource)
   at EVEStandard.EVEStandardAPI.initializeAPI()
   at EVEStandard.EVEStandardAPI..ctor(String userAgent, DataSource dataSource, TimeSpan timeOut)
   at EVEStandard.EVEStandardAPI..ctor(String userAgent, DataSource dataSource, TimeSpan timeOut, String callbackUri, String clientId, String secretKey)
   at xxxESI.SSO.TestEVEStandard() in xxxx
   at xxx.Form1.Button1_Click(Object sender, EventArgs e) in xxx

=== Pre-bind state information ===
LOG: DisplayName = Microsoft.Extensions.Logging.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
 (Fully-specified)
LOG: Appbase = file:///xxxx/
LOG: Initial PrivatePath = NULL
Calling assembly : EVEStandard, Version=2.0.9.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in default load context.
LOG: Using application configuration file: xxxx.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: Microsoft.Extensions.Logging.Abstractions, Version=2.1.1.0, Culture=neutral, PublicKeyToken=adb9793829ddae60
LOG: Attempting download of new URL file:///xxx/Microsoft.Extensions.Logging.Abstractions.DLL.
LOG: Attempting download of new URL file:///xxxx/Microsoft.Extensions.Logging.Abstractions/Microsoft.Extensions.Logging.Abstractions.DLL.
LOG: Attempting download of new URL file:///xxxxx/Microsoft.Extensions.Logging.Abstractions.EXE.
LOG: Attempting download of new URL file:///xxxx/Microsoft.Extensions.Logging.Abstractions/Microsoft.Extensions.Logging.Abstractions.EXE.

I am missing the 'Microsoft.Extensions.Logging.Abstractions' library. When I try to add it to the project from NuGet I got various problems, like wrong .NET Framework and etc.

Can you remove this dependency?  I have my own logging system and tons of references in the EVEStandard library does not help at all.

Off topic: can you make a sample Winforms app which covers the SSO?

thanks

**Comment by gehnster** [comment]
If I create a basic WinForms app in visual studio and add EVEStandard via NuGet I don't have any issues with NuGet trying to add the package. What version of .NET are you targeting? It needs to be .NET 4.6.1 or greater since I'm building as a .NET Standard 2.0 library. Try targeting WinForms to .NET 4.6.1 or higher.

As for the logging I will be keeping what I have in there. You are the first I've seen to have issues with it being in there and I've actually found it useful in troubleshoot issues other people have had in the past, if they enable it. That is the other thing, it SHOULD be optional. While you will have to download the dependencies for it, it shouldn't be enabled by default. You should have to use the AddLogging method to include logging from the library into whatever Microsoft.Extensions.Logging supported library you decide to use.

Finally, about the sample WinForms app showing how to use SSO with it. This is something I plan to do in the future, but not right now. Currently CCP's SSO functionality doesn't really support trying to do SSO with a desktop app. Yes, it can be done and people do it but its ugly. CCP is working on SSOv2 right now, I found out about it last week and took a look but it is still very buggy. It includes a proper way to do SSO from a desktop application. Once the implementation is stable-ish I will look into how to add to support for it in my library, and then create a sample WinForm or WPF app for it.

**Comment by nvpetrov** [comment]
thanks for the response

I was using earlier version of .NET Framework for my app. That's fixed now.

Can you share something, what a the steps to make a SSO with ESI?
Something like:
1. make new instance of EVEStandard.EVEStandardAPI
2. call EVEClient.SSO.AuthorizeToEVEUri
...
next?

what should be the callback url for the redirect and which app actually listen to this callback?

**Comment by gehnster** [comment]
Essentially its.

1. make instance of EVEStandardAPI
2. call EVEClient.SSO.AuthorizeToEVEUri
3. User click on link in returned Uri from step 2 and is taken to EVE Online Login page, they authorize one of their characters
4. User is redirected to callback you specified in your Developer application AND specified in step 1, if they don't match it fails.
5. You have some way to capture that callback, either with a web app controller end-point or a small web server setup, for desktop apps, and it's listening just for that callback.
6. You take code and state in that callback and follow lines 58 to 66 in that AuthController linked above. If you don't care about the state component then just set them both to some non-blank string.

Try checking out the basic code this person has, its a WPF app. They were having issues getting it to work and I helped them out a bit. Just don't steal the entire thing, it isn't open sourced. :) https://github.com/Meigs2/BUZZ

**Comment by nvpetrov** [comment]
Thanks.
Was looking for quick and dirty, but ended up reading the docs and making my own thing.
Worst thing - I am very very seasoned coder and still need to understand multi threading and async calls.

**Comment by gehnster** [comment]
MSDN has a great article about it. Essentially though what comes down to is anything I/O related you want to be async so UI doesn't pause during calls to I/O, especially true for a desktop app. You just end up having to put 'async' in the function definition and 'await' before any method you call that is async, helps to keep track what is and isn't an async method by putting Async at the end of its name.

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/concepts/async/

Also, feel free to join the Discord and ask questions there, unless you think it deserves a issue on here then feel free to post another one, but I think this one has been answered so I'll close it.
